spring:
  datasource:
    url: jdbc:mariadb://192.168.1.11:3306/task_engine
    username: caoxiao
    password: 1234qwer
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
