spring:
  datasource:
    url: jdbc:mariadb://zeebe.cn:3306/task_engine
    username: caoxiao
    password: 1234qwer
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
