spring:
  datasource:
    url: jdbc:mariadb://**.**.**.**:3306/task_engine
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 590000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
zeebe:
  client:
    broker:
      gatewayAddress: zeebe.cn:26500
    security:
      plaintext: true
